In [55]:
import numpy as np
import pickle

In [56]:
# Load the saved models
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('models/clf.pkl', 'rb'))

In [57]:
# User input 
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1, 7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [58]:
test_input_sex_encoded = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex_encoded

c:\Users\Admin\.conda\envs\python\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1.]])

In [59]:
test_input_embarked_encoded = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked_encoded

array([[0., 1.]])

In [60]:
test_input_age = test_input[:,2].reshape(1,1)
test_input_age


array([[31.0]], dtype=object)

In [61]:
# Concatinating all the data 
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex_encoded,test_input_embarked_encoded),axis=1)
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 1.0, 0.0, 1.0]], dtype=object)

In [62]:
test_input_transformed.shape

(1, 8)

In [63]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

When we manually preprocess features and save separate encoders and models, deploying a machine learning solution can get messy. Every time new data comes in, we have to remember to encode features like **sex** or **embarked**, and if we change something in the original workflow, we have to update the deployment code by hand. Pipelines make this much easier—they bundle all the preprocessing steps and the model into one object. This way, new data flows through the same transformations automatically, and predictions can be made right away. Pipelines make deployment **cleaner, safer, and hassle-free**, and any updates in the original workflow automatically carry over.