In [4]:
import numpy as np
import pandas as pd
import random

from sklearn.datasets import load_diabetes
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [5]:
X,y = load_diabetes(return_X_y=True)

In [8]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
mbgd = SGDRegressor(learning_rate='constant',eta0=0.01)

In [10]:
epochs = 100
batch_size = 36

for i in range(epochs):
    ran_batch = random.sample(range(X_train.shape[0]),batch_size)
    mbgd.partial_fit(X_train[ran_batch],y_train[ran_batch])

In [11]:
mbgd.intercept_

array([149.06840647])

In [12]:
mbgd.coef_

array([ 22.11091698,  -5.06880394,  77.22339744,  52.69424004,
        18.52148898,  13.55539169, -45.11553852,  47.15642437,
        65.002798  ,  46.18139443])

In [14]:
y_pred = mbgd.predict(X_test)

In [15]:
r2_score(y_test,y_pred)

0.18861545498214494